env:
  node: true
  es2020: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 11
rules:
  no-var:
    - error
  prefer-const:
    - error
  prefer-arrow-callback:
    - error
  no-unused-vars:
    - error
    - varsIgnorePattern: "logger"
      argsIgnorePattern: "^_"
overrides:
- files: ["*.spec.*js"]
  rules:
    no-unused-vars: off
    no-undef: off
