name: Automated Deployment
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Automated Deploy
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        KEYFILE=~/.ssh/bb_bot_key
        mkdir ~/.ssh
        touch ${KEYFILE}
        echo "${SSH_KEY}" > "${KEYFILE}"
        chmod 400 "${KEYFILE}"
        SSH_OPTS="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        ssh ${SSH_OPTS} -i "${KEYFILE}" "bb_bot@${SSH_HOST}" "sudo /opt/bb_bot/deployment/update.sh"
